version: '1.0'
name: pipeline-20221016
displayName: 每日一题脚本
triggers:
  trigger: auto
  schedule:
    - cron: '* 0 0 ? * 1 *'
stages:
  - name: stage-a9981f56
    displayName: 切分支
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: script 构建
        nodeVersion: 14.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - ''
          - npm config set registry https://registry.npmmirror.com
          - pwd
          - ls
          - '# 执行编译命令'
          - cd script && npm install
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
